import 'dart:ffi';

class Ticker {
  final String symbol; //"symbol": "MGLU3",
  final String shortName; //"shortName": "MAGAZ LUIZA ON      NM",
  final String longName; //"longName": "Magazine Luiza S.A.",
  final String currency; //"currency": "BRL",
  final Double regularMarketPrice; //"regularMarketPrice": 3.03,
  final Double regularMarketDayHigh; //"regularMarketDayHigh": 3.11,
  final Double regularMarketDayLow; //"regularMarketDayLow": 2.9,
  final String regularMarketDayRange; //"regularMarketDayRange": "2.9 - 3.11",
  final Double regularMarketChange; //"regularMarketChange": -0.01999998,
  final Double
      regularMarketChangePercent; //"regularMarketChangePercent": -0.6557371,
  final String
      regularMarketTime; //"regularMarketTime": "2023-01-11T21:07:44.000Z",
  final Int32 marketCap; //"marketCap": 20627390464,
  final Int32 regularMarketVolume; //"regularMarketVolume": 170364500,
  final Double regularMarketPreviousClose; //"regularMarketPreviousClose": 3.05,
  final Double regularMarketOpen; //"regularMarketOpen": 3.07,
  final Int32 averageDailyVolume10Day; //"averageDailyVolume10Day": 151044755,
  final Int32 averageDailyVolume3Month; //"averageDailyVolume3Month": 196588019,
  final Double fiftyTwoWeekLowChange; //"fiftyTwoWeekLowChange": 1,
  final Double
      fiftyTwoWeekLowChangePercent; //"fiftyTwoWeekLowChangePercent": 0.49261084,
  final String fiftyTwoWeekRange; //"fiftyTwoWeekRange": "2.03 - 7.38",
  final Double fiftyTwoWeekHighChange; //"fiftyTwoWeekHighChange": -4.3500004,
  final Double
      fiftyTwoWeekHighChangePercent; //"fiftyTwoWeekHighChangePercent": -0.5894309,
  final Double fiftyTwoWeekLow; //"fiftyTwoWeekLow": 2.03,
  final Double fiftyTwoWeekHigh; //"fiftyTwoWeekHigh": 7.38,
  final Double twoHundredDayAverage; //"twoHundredDayAverage": 3.77985,
  final Double
      twoHundredDayAverageChange; //"twoHundredDayAverageChange": -0.74985003,
  final Double
      twoHundredDayAverageChangePercent; //"twoHundredDayAverageChangePercent": -0.1983809,
  final Double priceEarnings; //"priceEarnings": null,
  final Double earningsPerShare; //"earningsPerShare": -0.0554488,
  final String
      logourl; //"logourl": "https://s3-symbol-logo.tradingview.com/magaz-luiza-on-nm--big.svg"

  Ticker(
    this.symbol,
    this.shortName,
    this.longName,
    this.currency,
    this.regularMarketPrice,
    this.regularMarketDayHigh,
    this.regularMarketDayLow,
    this.regularMarketDayRange,
    this.regularMarketChange,
    this.regularMarketChangePercent,
    this.regularMarketTime,
    this.marketCap,
    this.regularMarketVolume,
    this.regularMarketPreviousClose,
    this.regularMarketOpen,
    this.averageDailyVolume10Day,
    this.averageDailyVolume3Month,
    this.fiftyTwoWeekLowChange,
    this.fiftyTwoWeekLowChangePercent,
    this.fiftyTwoWeekRange,
    this.fiftyTwoWeekHighChange,
    this.fiftyTwoWeekHighChangePercent,
    this.fiftyTwoWeekLow,
    this.fiftyTwoWeekHigh,
    this.twoHundredDayAverage,
    this.twoHundredDayAverageChange,
    this.twoHundredDayAverageChangePercent,
    this.priceEarnings,
    this.earningsPerShare,
    this.logourl,
  );

  factory Ticker.fromJson(Map<List<Ticker>, dynamic> json) {
    return json['results'].map((key, value) => Ticker(
          value.symbol,
          value.shortName,
          value.longName,
          value.currency,
          value.regularMarketPrice,
          value.regularMarketDayHigh,
          value.regularMarketDayLow,
          value.regularMarketDayRange,
          value.regularMarketChange,
          value.regularMarketChangePercent,
          value.regularMarketTime,
          value.marketCap,
          value.regularMarketVolume,
          value.regularMarketPreviousClose,
          value.regularMarketOpen,
          value.averageDailyVolume10Day,
          value.averageDailyVolume3Month,
          value.fiftyTwoWeekLowChange,
          value.fiftyTwoWeekLowChangePercent,
          value.fiftyTwoWeekRange,
          value.fiftyTwoWeekHighChange,
          value.fiftyTwoWeekHighChangePercent,
          value.fiftyTwoWeekLow,
          value.fiftyTwoWeekHigh,
          value.twoHundredDayAverage,
          value.twoHundredDayAverageChange,
          value.twoHundredDayAverageChangePercent,
          value.priceEarnings,
          value.earningsPerShare,
          value.logourl,
        ));
  }
}
